### ISSUE TITLE
Add Constants module

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-units#19]
This would be a central place to store conversion factors, useful for a couple reasons:

  - Avoid duplication when the same constants are used in multiple modules (e.g. `Mass` and `Volume` constants reused in `Density` module)
  - Be a single place to record what reference each constant was taken from (see #10)

**Comment by katjam** [comment]
@ianmackenzie Hoping to have a few hours to spare in the next week or so. I'll have a go at this one.

**Comment by ianmackenzie** [comment]
Excellent, sounds great @katjam! I'm currently working on #22, but I don't think that should conflict with this. Adding better product support will really only touch `Quantity.elm` (with the exception of changing the definition of `Newtons` in `Force.elm` from `Rate Joules Meters` to `Product Kilograms MetersPerSecondSquared`), whereas adding a constants module will touch basically everything _except_ `Quantity.elm`.

I may end up pushing out a new major release soon with the expanded product support - I don't think it really makes much of a difference whether adding a constants module gets merged in before or after that happens. (Although perhaps not _right_ before...)

**Comment by katjam** [comment]
Agree. Sounds unlikely that we'll tread on each other's toes. Toying with name stuff. I guess we've agreed `Constants.elm` as the module - but would `SharedConstants.elm` (if we aren't pulling all of them out) or `ConversionFactors.elm` be any more explanatory?

Unless you say otherwise, I'll assume we:
- call the module `Constants.elm`
- aim to pull all of the conversion factors out - starting with the shared ones (so that we can get the patterns/ format agreed before I move everything)
- are heading for a single source of truth for references (see #10)

**Comment by ianmackenzie** [comment]
The module name might depend on what pattern we use for the actual constant names - for example I could see either `Constants.foot` (a constant representing the length of one foot in SI units) or `ConversionFactors.metersPerFoot`/`ConversionFactors.feetPerMeter`. The second seems more explicit although the first is a bit more concise/composable, e.g.

```elm
cubicFoot =
    foot * foot * foot
```

instead of

```elm
cubicMetersPerCubicFoot =
    metersPerFoot * metersPerFoot * metersPerFoot
```

Probably worth playing around with a few different styles and see what seems best (both at call sites and within the module itself), but I think I'm leaning slightly towards the second (["there are worse things than being explicit"](https://twitter.com/czaplic/status/928359033844539393)!). I think you'd end up with both 'direct' and 'inverse' conversion factors in `ConversionFactors.elm`, like

```elm
module ConversionFactors

metersPerFoot : Float
metersPerFoot =
    0.3048

feetPerMeter : Float
feetPerMeter =
    1 / metersPerFoot
```

(or perhaps `feetToMeters` and `metersToFeet`?) which might be used like

```elm
module Length

import ConversionFactors

feet : Float -> Length
feet numFeet =
    meters (numFeet * ConversionFactors.metersPerFoot)

inFeet : Length -> Float
inFeet length =
    inMeters length * ConversionFactors.feetPerMeter
```

Lastly, while I think it makes sense to _start_ with the shared constants, I think my preference would be to eventually move _all_ constants/conversion factors into the single module (for consistency, and so it's easier to check all of them against a reference).

**Comment by katjam** [comment]
Sounds like we are thinking along the same lines. Maybe both natural over-thinkers. I'll see how I get on one step at a time, leaving the PR open for comment.
