### ISSUE TITLE
Move more constants to Constants.elm

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-units#29]
Good candidates:

 - [ ] parsec, astrounit, lightyear (Lengths)
 - [ ] gee (Acceleration)
 - [ ] pounds force (Force)
 - [ ] julian years (Duration)
 - [ ] long ton, short ton (Mass)
 - [ ] atmosphere in Pascals (Pressure)
 - [ ] metric, mechanical & electric horsepower (Power)

**Comment by mankalas** [comment]
Resolved [here](https://github.com/mankalas/elm-units/commit/08ef50d944f97b5490b49b1b47364823bc7da3f8)

**Comment by carlosfrodrigues** [comment]
Hi, could you assign this issue to me?

**Comment by ianmackenzie** [comment]
Done - go for it!
