### ISSUE TITLE
Add tests for Quantity.[positive,negative]Infinity

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-units#33]
Check that they are greater than/less than any randomly generated finite value, just in case Elm ever redefines 1/0 to be 0 or NaN or something

**Comment by miguelcarvalho13** [comment]
Hi! Can I help with this issue?

**Comment by ianmackenzie** [comment]
Certainly! I've gone ahead and assigned it to you, let me know if you have any questions or want more detail 🙂

**Comment by miguelcarvalho13** [comment]
Hi @ianmackenzie thanks to assigning it to me!
Just tried to do a PR adding the tests https://github.com/ianmackenzie/elm-units/pull/56.
If there's something wrong/missing just let me know! 😄
