### ISSUE TITLE
Add Quantity.in_?

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-units#34]
Alternative to using `Length.inMeters`, `Duration.inHours` etc.:

```elm
in_ : (Float -> Quantity Float units) -> Quantity Float units -> Float
in_ units quantity =
    ratio quantity (units 1)
```

Would be used like

```elm
length =
    Length.feet 1

Quantity.in_ Length.meters length
--> 0.3048
```

This would have a few advantages: could avoid having confusing function names like `Pixels.inPixels` and instead use

```elm
screenLength |> Quantity.in_ Pixels.pixels
```

Also allows for converting to weird custom units pretty easily, like getting speed in millimeters per minute:

```elm
Speed.metersPerSecond 0.001
    |> Quantity.in_ (Length.millimeters >> Quantity.per (Duration.minutes 1))
--> 60
```

However, it's more verbose than the current dedicated functions and would be a bit less efficient.

**Comment by harrysarson** [comment]
Is this the same as #27?

**Comment by ianmackenzie** [comment]
Oops, yes it absolutely is! I'll close this as a duplicate.
