### ISSUE TITLE
Add modBy function(s)

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-units#46]
Should ideally support both `Int` and `Float` quantities, but it's likely not possible to come up with a generic `number` version that satisfies the type checker; in that case what should the two names of the two different functions be?

**Comment by ianmackenzie** [comment]
Possibilities:

- `modBy`/`fractionalModBy`
- `integralModBy`/`modBy`
- `integralModBy`/`fractionalModBy`
- `modBy`/`fmodBy`

**Comment by MartinSStewart** [comment]
I think `modBy` and `fractionalModBy` should be used to be consistent with `elm/core` and [elm-community/basics-extra](https://package.elm-lang.org/packages/elm-community/basics-extra/latest/Basics-Extra#fractionalModBy).

**Comment by ianmackenzie** [comment]
Yeah, that probably makes sense. I think part of me was hoping to figure out some way that the `Float` version could be the 'default' version, since I think `Float`-valued quantities are significantly more common than `Int`-valued ones, but it's probably better to just be consistent with existing packages.

**Comment by MartinSStewart** [comment]
You could write `modBy` like this:
```elm
modBy : number -> number -> number
modBy mod value =
    if value > mod then
        modBy mod (value - mod)
    else if value < 0 then
        modBy mod (value + mod)
    else 
        value
```
but it would be terribly slow. A faster version could do a binary search to find what value `n` makes `n * mod <= value` and `(n + 1) * mod > value` and then return `value - n * mod`. Still slow, but if you *really* want to have consistency with existing names and not make the float version second class then I guess you could do this.

**Comment by ianmackenzie** [comment]
Cool idea! But yeah, I agree, not worth the likely performance cost.

**Comment by ianmackenzie** [comment]
@MartinSStewart any chance you could take a look at the changes in a7a2d31644fd2d2c6d36a55ed22df1e7638ef9cf and see if they look OK? I did add some tests to make sure my `fractionalModBy` and `fractionalRemainderBy` implementations were consistent with `modBy` and `remainderBy` from `elm/core`, but I'm still slightly fuzzy on the precise definitions of the two operations.

**Comment by MartinSStewart** [comment]
Looks good to me! At the very least, your implementation matches `elm/core` and `elm/basics-extra`.

**Comment by ianmackenzie** [comment]
Yeah, I figured that since `elm/core` has both `modBy` and `remainderBy` it would be ideal to support `Quantity` versions of both. Glad the fuzzer makes sense, and thanks for taking a look - definitely gives me a bit more confidence!
